var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/verificar-correo/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1lq2zv7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17p0jfa._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15ypo8t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/[root-of-the-server]__0utrwge._.js")
R.c("server/chunks/ssr/_06lz9sj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_18_d8l1._.js")
R.c("server/chunks/ssr/node_modules_@supabase_supabase-js_dist_index_mjs_087pi7g._.js")
R.c("server/chunks/ssr/node_modules_next_17sz44y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_verificar-correo_page_actions_1d4-pt9.js")
R.m(69059)
module.exports=R.m(69059).exports
