import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Un nonce de CSP es, por definicion, distinto en cada peticion: un HTML
 * generado durante el build no puede llevarlo.
 *
 * Sin esto, `next build` prerenderizaba /login, /panel, / y las demas a
 * .next/server/app/*.html y `next start` devolvia ese archivo tal cual
 * (comprobado: el HTML servido era byte a byte identico al del build).
 * app-render -- que es quien lee la CSP de la PETICION y le pone el nonce a
 * los <script> de Next -- no llegaba a ejecutarse. Y como la politica lleva
 * 'strict-dynamic', el navegador ignora 'self': esos <script> sin nonce
 * quedaban bloqueados y la pagina no hidrataba.
 *
 * force-dynamic en el layout raiz se propaga a todos los segmentos de abajo.
 * Se paga el prerender estatico: ese es el precio inevitable de un nonce por
 * peticion, no una limitacion de esta implementacion. Si el SP1 necesita
 * cachear el catalogo publico, la salida no es quitar el nonce sino servir esa
 * ruta con una politica propia sin 'strict-dynamic'.
 */
export const dynamic = "force-dynamic";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
