import { describe, it, expect, vi } from 'vitest'

// next/font/google solo resuelve dentro del compilador de Next. Mismo mock que
// en render-dinamico.test.ts: aqui no se prueba la tipografia.
vi.mock('next/font/google', () => ({
  Geist: () => ({ variable: 'geist' }),
  Geist_Mono: () => ({ variable: 'geist-mono' }),
}))

/**
 * Seguimiento S5.
 *
 * El layout raiz venia con los valores que deja `create-next-app`: title
 * "Create Next App", description "Generated by create next app" y `lang="en"`
 * en una aplicacion escrita entera en espanol.
 *
 * Los dos primeros son la pestana del navegador y lo que aparece en un
 * resultado de busqueda o en la vista previa de un enlace compartido. El
 * tercero pesa mas de lo que parece: `lang` es lo que usa un lector de
 * pantalla para elegir la voz y la pronunciacion, y lo que usan el navegador y
 * los buscadores para saber en que idioma esta el contenido. Con `en`, un
 * usuario ciego oye el portal leido con fonetica inglesa.
 *
 * No se comprueba el texto exacto -- puede cambiar -- sino que no se haya
 * vuelto a la plantilla y que el idioma declarado sea el que se escribe.
 */
describe('metadatos del layout raiz', () => {
  it('no conserva los valores de create-next-app', async () => {
    const { metadata } = await import('../../src/app/layout')

    expect(metadata.title).toBeTruthy()
    expect(metadata.description).toBeTruthy()
    expect(metadata.title).not.toMatch(/create next app/i)
    expect(metadata.description).not.toMatch(/create next app/i)
  })

  it('declara el documento en espanol', async () => {
    const layout = await import('../../src/app/layout')

    // Se inspecciona el elemento que devuelve el componente, sin renderizarlo:
    // el atributo lang vive en sus props y no hace falta un DOM para leerlo.
    const elemento = layout.default({ children: null } as never) as unknown as {
      props: { lang?: string }
    }

    expect(elemento.props.lang).toBe('es')
  })
})
